/* https://tailwindcss.com/docs/configuration */

module.exports = {
	content: ['./resources/views/**/*.{html,js,twig}'],
	theme: {
		fontFamily: {
			body: ['Barlow', 'Franklin Gothic Medium', 'Tahoma', 'sans-serif'],
			header: [
				'IBM Plex Sans',
				'Impact',
				'Franklin Gothic Bold',
				'sans-serif',
			],
			subheader: [
				'Oswald',
				'Impact',
				'Franklin Gothic Bold',
				'sans-serif',
			],
		},
		fontSize: {
			'-ms-3': "11px",
			'-ms-2': "12px",
			'-ms-1': "14px",
			'ms-0': "16px",
			'ms-1': "18px",
			'ms-2': "20px",
			'ms-3': "22px",
			'ms-4': "25px",
			'ms-5': "28px",
			'ms-6': "32px",
			'ms-7': "36px",
			'ms-8': "41px",
			'ms-9': "46px",
			'ms-10': "51px",
			'ms-11': "58px",
			'ms-12': "65px",
			'ms-13': "73px",
		},
		colors: {
			// Primary, secondary, tertiary should have the main brand colors,
			// then up-shade and down-shade for the light and dark versions
			primary: {
				light: '#e52560',
				DEFAULT: '#a01b44',
				dark: '#710627',
				fg: '#fff',
			},
			secondary: {
				light: '#fdf0a9',
				DEFAULT: '#dbc764',
				dark: '#d0b635',
				fg: '#000',
			},
			tertiary: {
				light: '#d3356c',
				DEFAULT: '#a01b44',
				dark: '#710627',
				fg: '#fff',
			},
			// Accents should be added as numeric items
			accent: {
				1: '#333',
				2: '#999',
				3: '#ddd',
			},
			grey: {
				100: '#f1f1f1',
				300: '#d2d2d2',
				500: '#9a9a9a',
				700: '#5a5a5a',
				900: '#1a1818',
			},
			black: {
				transparent: 'rgba(0,0,0,0.7)',
				DEFAULT: '#1a1818',
			},
			white: {
				transparent: 'rgba(255,255,255,0.7)',
				DEFAULT: '#fefefe',
			},
			transparent: 'rgba(0,0,0,0)',
			feedback: {
				success: '#6dcff6',
				warning: '#fdf0a9',
				error: '#f69679',
			},
			social: {
				facebook: '#3b5998',
				flickr: '#ff0084',
				houzz: '#7ac142',
				instagram: '#833ab4',
				linkedin: '#0976b4',
				medium: 'rgba(0, 0, 0, 0.84)',
				pinterest: '#cc2127',
				rss: '#f26522',
				tumblr: '#35465c',
				twitter: '#55acee',
				youtube: '#b31217',
				vimeo: '#1ab7ea',
				yelp: '#f43939',
			},
			color: {
				link: '#a01b44',
				'field': '#E4EEF7',
				'field-required': '#F2EED6',
			},
		},
		containers: {
			sm: "640px",
			md: "768px",
			lg: "1024px",
			xl: "1280px",
			'2xl': "1536px",
			'3xl': "1800px",
			DEFAULT: "1536px",
			padding: '1.5rem',
		},
		extend: {},
		richtext: ({ theme }) => ({
			backgroundColors: {
				'table-td': 'inherit',
				'table-th': theme('colors.primary.DEFAULT'),
			},
			borderColors: {
				'table-td': theme('colors.grey.300'),
				'table-th': theme('colors.primary.light'),
			},
			colors: {
				bullet: theme('colors.primary.DEFAULT'),
				blockquote: theme('colors.grey.900'),
				link: theme('colors.primary.DEFAULT'),
				'table-td': theme('colors.grey.900'),
				'table-th': theme('colors.white.DEFAULT'),
			},
			fontFamily: {
				'table-td': theme('fontFamily.body'),
				'table-th': theme('fontFamily.subheader'),
			},
			fontSize: {
				blockquote: "20px",
				'heading-1': "36px",
				'heading-2': "31px",
				'heading-3': "28px",
				'heading-4': "25px",
				'heading-5': "22px",
				'heading-6': "20px",
				'table-td': "20px",
				'table-th': "22px",
			},
			fontWeight: {
				base: 400,
				blockquote: 700,
				bullet: 700,
				'heading-1': 700,
				'heading-2': 700,
				'heading-3': 700,
				'heading-4': 700,
				'heading-5': 700,
				'heading-6': 700,
				'table-td': 400,
				'table-th': 700,
			},
			spacing: {
				DEFAULT: '1rem',
				hr: '2rem',
				header: '2.5rem',
				gallery: '3rem',
				list: '1rem',
			},
		}),
	},
	corePlugins: {
		container: false,
	},
	plugins: [
		require('@tailwindcss/forms'),
	],
};
